name: wgpu_example
description: Demonstrates how to use the wgpu plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  wgpu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
