name: wgpu
description: Experimental WebGPU plugin
version: 0.0.0
homepage: https://github.com/jpnurmi/flutter_wgpu
repository: https://github.com/jpnurmi/flutter_wgpu
issue_tracker: https://github.com/jpnurmi/flutter_wgpu/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  wgpu_ffi: #^0.0.0-nullsafety.0
    path: ../../dart/dart_wgpu_ffi
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^2.0.0-nullsafety.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WgpuPlugin
      macos:
        pluginClass: WgpuPlugin
      windows:
        pluginClass: WgpuPlugin
